# .travis.yml

language: php

sudo: false

php:
  - 7.0

script:
  # Run your tests here.
  - echo 'Tested'
before_deploy:
  - "./src/lib/oyst-php-master/get-sdk.sh"

after_deploy:
  - "./scripts/deploy.sh"

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
    - scripts/deploy.sh
  on:
    tags: true
    condition: "$AUTO_DEPLOY = true"

notifications:
  email:
    on_success: never  # options: [always|never|change] default: change
    on_failure: never  # options: [always|never|change] default: always
  slack:
    template:
      - "build by %{author} in %{duration}"
      - "%{repository_name,} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
      - "%{result}"
    on_success: always
    on_failure: always
    rooms: oystteam:6e4bjreOFmXp3veCeGfcCJRA#4tests