# .travis.yml

language: php

sudo: false

php:
  - 7.0
  - 7.1

script:
  # Run your tests here.
  - echo 'Tested'

deploy:
  #
  # Auto-deploys the built plugin to WordPress.org on push to master branch
  #
  provider: script
  skip_cleanup: true
  script: "./scripts/deploy.sh"
  on:
    branch: master
