#! /bin/bash

CURRENTDIR=`pwd`
PLUGINSLUG="woo-oyst"
SVNPATH="/tmp/$PLUGINSLUG"
SVNURL="http://plugins.svn.wordpress.org/$PLUGINSLUG"
SVNUSER="oyst1click"
SVNPWD=WP_ORG_PASSWORD
PLUGINDIR=CURRENTDIR
MAINFILE="$PLUGINSLUG.php"

echo CURRENTDIR
echo PLUGINSLUG
echo SVNPATH
echo SVNURL
echo SVNUSER
echo SVNPWD
echo PLUGINDIR
echo MAINFILE
